### ISSUE TITLE
Plugin "enabled" but doesn't function in Vault 0.10.1

### ISSUE THREAD

**Issue by MadOtis** [hashicorp/vault-auth-plugin-example#7] opened 2018-05-23 22:30 UTC
I am learning to write an Auth plugin for Vault to meet a need we have at work.  So, I started from this source, as I see it has been updated in the past few days, so it should be the most up-to-date.

I cloned the repo and everything built as expected (I chose the go build output of "foo").  I ran these steps (as described in the readme):

```
:---> vault login root
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                Value
---                -----
token              root
token_accessor     d3da63ad-bd47-7aa7-6e73-a38212c38b4f
token_duration     ∞
token_renewable    false
token_policies     [root]
[bn2s]@[vault-auth-plugin-example]
:---> vault write sys/plugins/catalog/example sha_256="$SHA256" command="foo"
Success! Data written to: sys/plugins/catalog/example
[bn2s]@[vault-auth-plugin-example]
:---> vault auth enable -path=example -plugin-name=example plugin
Success! Enabled example plugin at: example/
[bn2s]@[vault-auth-plugin-example]
:---> vault write auth/example/login password=foo
Error writing data to auth/example/login: Error making API request.

URL: PUT http://localhost:8200/v1/auth/example/login
Code: 500. Errors:

* plugin exited before we could connect
[bn2s]@[vault-auth-plugin-example]
:---> echo $SHA256
fe64aa4731d5a5d1cff7b439e5bf538dc08b9dee6c18f1d9b2c8a201206c4fe5
[bn2s]@[vault-auth-plugin-example]
:--->

```
With this debug output from Vault running in local DEV mode (truncated for brevity):
```
2018-05-23T15:20:46.844-0700 [DEBUG] auth.plugin.auth_plugin_d4568bbb.example: starting plugin: path=/Users/bn2s/go/src/github.com/hashicorp/vault-auth-plugin-example/foo args=[/Users/bn2s/go/src/github.com/hashicorp/vault-auth-plugin-example/foo]
2018-05-23T15:20:46.848-0700 [DEBUG] auth.plugin.auth_plugin_d4568bbb.example: waiting for RPC address: path=/Users/bn2s/go/src/github.com/hashicorp/vault-auth-plugin-example/foo
2018-05-23T15:20:46.890-0700 [ERROR] auth.plugin.auth_plugin_d4568bbb.example.foo: plugin tls init: error="error during token unwrap request: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/wrapping/unwrap
Code: 403. Errors:

* permission denied" timestamp=2018-05-23T15:20:46.889-0700
2018-05-23T15:20:46.891-0700 [DEBUG] auth.plugin.auth_plugin_d4568bbb.example: plugin process exited: path=/Users/bn2s/go/src/github.com/hashicorp/vault-auth-plugin-example/foo
2018-05-23T15:20:46.891-0700 [ERROR] rollback: error rolling back: path=auth/example/ error="plugin exited before we could connect"
2018-05-23T15:20:49.439-0700 [DEBUG] auth.plugin.auth_plugin_d4568bbb.example: starting plugin: path=/Users/bn2s/go/src/github.com/hashicorp/vault-auth-plugin-example/foo args=[/Users/bn2s/go/src/github.com/hashicorp/vault-auth-plugin-example/foo]
2018-05-23T15:20:49.442-0700 [DEBUG] auth.plugin.auth_plugin_d4568bbb.example: waiting for RPC address: path=/Users/bn2s/go/src/github.com/hashicorp/vault-auth-plugin-example/foo
2018-05-23T15:20:49.484-0700 [ERROR] auth.plugin.auth_plugin_d4568bbb.example.foo: plugin tls init: error="error during token unwrap request: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/wrapping/unwrap
Code: 403. Errors:

```

ok, so I think to myself that I must have done something wrong, or mistakenly changed some of the code...  So, I blow away the clone, and re-cloned it...  Rebuild, re-start Vault, and try again.  Same results.

So, while this appears to ENABLE properly in 0.10.1, it doesn't seem to RUN in 0.10.1.  I would expect it to work so I can use it as a basis for implementing a real (read: secure, valid, production-ready) auth plugin from it.

**Comment by jefferai** [comment] 2018-05-24 15:31
Duplicate of https://github.com/hashicorp/vault/issues/4630

**Closed by jefferai** 2018-05-24 15:31 UTC
